// @generated by ffi_introspect --emit-widgets-rs; do not edit
#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct FfiPositionDto {
    pub x: u16,
    pub y: u16,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct FfiRect {
    pub x: u16,
    pub y: u16,
    pub width: u16,
    pub height: u16,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct FfiOffsetDto {
    pub x: i32,
    pub y: i32,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct FfiMarginDto {
    pub horizontal: u16,
    pub vertical: u16,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, Default)]
pub struct FfiSizeDto {
    pub width: u16,
    pub height: u16,
}

