// @generated by ffi_introspect --emit-enums-rs; do not edit
// These enums are ABI-stable u32 mirrors of upstream enums.
// They intentionally avoid payloads and lifetimes; variants map by name.
#[repr(u32)]
pub enum FfiAlign {
    Center = 0,
    Left,
    Right,
}

#[repr(u32)]
pub enum FfiDirection {
    Horizontal = 0,
    Vertical,
}

#[repr(u32)]
pub enum FfiFlex {
    Center = 0,
    End,
    Legacy,
    SpaceAround,
    SpaceBetween,
    Start,
}

#[repr(u32)]
pub enum FfiMarker {
    Bar = 0,
    Block,
    Braille,
    Dot,
    HalfBlock,
}

#[repr(u32)]
pub enum FfiPosition {
    Bottom = 0,
    Top,
}

#[repr(u32)]
pub enum FfiBorderType {
    Double = 0,
    Plain,
    QuadrantInside,
    QuadrantOutside,
    Rounded,
    Thick,
}

#[repr(u32)]
pub enum FfiGraphType {
    Bar = 0,
    Line,
    Scatter,
}

#[repr(u32)]
pub enum FfiLegendPosition {
    Bottom = 0,
    BottomLeft,
    BottomRight,
    Left,
    Right,
    Top,
    TopLeft,
    TopRight,
}

#[repr(u32)]
pub enum FfiListDirection {
    BottomToTop = 0,
    TopToBottom,
}

#[repr(u32)]
pub enum FfiRenderDirection {
    LeftToRight = 0,
    RightToLeft,
}

