name: ci

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rid: linux-x64
          - os: windows-latest
            rid: win-x64
          - os: macos-13
            rid: osx-x64
          - os: macos-14
            rid: osx-arm64
        feature: [default, ffi_safety]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: |
          if [ "${{ matrix.feature }}" = "ffi_safety" ]; then \
            cargo build --release --features ffi_safety; \
          else \
            cargo build --release; \
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rid }}-${{ matrix.feature }}
          path: |
            target/release/*.so
            target/release/*.dll
            target/release/*.dylib
